### ISSUE TITLE
Fail to get the file discriptor?

### ISSUE THREAD

**Issue by Userzxcvbvnm** [wasmerio/wasmer#4753] opened 2024-05-27 11:24 UTC
### Describe the bug
Fail to get the file descriptor, while other Wasm runtimes and native could get it successfully.

### Steps to reproduce
The c file is :
```
#include <stdio.h>
#include <fcntl.h>
#include <unistd.h>


int get_fd(const char *filename, int flags) {
    int fd = open(filename, flags);
    
    if (fd == -1) {
        printf("Get file descriptor of file %s failed!\n", filename);
        return -1;
    } else {
        printf("Get file descriptor of file %s succeed!\n", filename);
        return fd;
    }
}


int main() {
    int fd = get_fd("./hello.txt", O_RDWR);
    return 0;
}
```

(1)compile to Wasm:
`./wasi-sdk-21.0/bin/clang --target=wasm32-unkown-wasi --sysroot=./wasi-sdk-21.0/share/wasi-sysroot read.c -o read.wasm`
(2)compile to native code:
`gcc read.c -o read`
(3)Running wasm:
`wasmer run --dir=. read.wasm`
(4)Running native binaries
`./read`

### Expected behavior
Output:
`Get file descriptor of file ./hello.txt succeed!`
And this is the output of native and other Wasm runtimes, such as wasmtime.

### Actual behavior
wasmer prints:
`Get file descriptor of file ./hello.txt failed!`

### Additional context
Ubuntu 20.04
wasmer-4.3.1

**Comment by Userzxcvbvnm** [comment] 2024-05-29 04:12
It seems wasmer could ont open any file, whether native and other runtimes could.

**Comment by maminrayej** [comment] 2024-05-29 06:27
@Userzxcvbvnm could you please test your use case with #4730? since I believe this is a duplicate of #4724.

**Comment by Userzxcvbvnm** [comment] 2024-05-30 02:14
I tried my test case with the wasmer of commit 4730, but failed again with the same output I mentioned.
The steps are:
(1) `git clone https://github.com/wasmerio/wasmer.git`
(2)'git reset --hard 6aee08d6b0e1b9a9cc38e6bef0e93c0aa3f52fe1' (set to commit 4730)
(3)'make build-wasmer'
(4)'wasmer run --dir=. read.wasm'
Print:
```
Get file descriptor of file ./hello.txt failed!
```

**Comment by maminrayej** [comment] 2024-05-30 07:51
Thanks for testing. I'll investigate.

**Comment by maminrayej** [comment] 2024-05-30 11:36
I can confirm your provided example, now works using the latest commit of #4730.

**Closed** 2024-05-31 11:49 UTC
Labels: 📦 lib-vfs, priority-high

**Comment by Userzxcvbvnm** [comment] 2024-06-01 02:23
Thanks for your reply and commit!
I reproduced the test by setting Wasmer to commit d202535dd2c75b8efa4aaf82a10fcdcb5c79328c(the newest 4730 commit). However, I still get the result `Get file descriptor of file ./hello.txt failed!`.
Is there anything wrong with my command or with your code?
