### ISSUE TITLE
Java

### ISSUE THREAD

**Issue by VictorPinas** [wasmerio/wasmer#1000] opened 2019-11-22 02:16 UTC
Thanks for proposing a new feature!

### Motivation

A clear and concise description of what the motivation for the new feature is, and what problem it is solving.

### Proposed solution

A clear and concise description of the feature you would like to add, and how it solves the motivating problem.

### Alternatives

A clear and concise description of any alternative solutions or features you've considered, and why you're proposed solution is better.

**Comment by syrusakbary** [comment] 2019-12-11 08:31
This issue seems a duplicate of #950. Closing it :)

**Closed by syrusakbary** 2019-12-11 08:31 UTC
Labels: 🎉 enhancement
