### ISSUE TITLE
wasmer run {url} interprets c:// file paths as URLs on Windows

### ISSUE THREAD

**Issue by gerjandev** [wasmerio/wasmer#3366] opened 2022-11-24 10:33 UTC
### Describe the bug

I get the following error:

```
>  wapm run cowsay
error: error fetching c:\Users\username\wapm_packages\syrusakbary/cowsay@0.2.0\target/wasm32-wasi/release/cowsay.wasm: get_webc_bytes failed
```

```
> wasmer -V
wasmer 3.0.1
```

### Steps to reproduce
Run above command on Windows

### Expected behavior
Output from cowsay

### Actual behavior
Error, see above

**Comment by fschutt** [comment] 2022-11-24 15:50
I could reproduce this, it seems that this was a bug from the migration from wapm run to wasmer run: wapm run creates a file `cowsay.cmd` in `~/wapm_packages/.bin` with the content:

```
@"wapm" run cowsay %*
```

When the command is executed, wasmer will be invoked with the path to the file, and for some reason it interprets the file path as a Url. This seems to only happen on Windows because Windows file paths start with `C://`, which gets parsed into a Url like `http://`. So it will try to fetch the file from the network and fail at that.

As a workaround `wasmer run cowsay` does work, even though there is some output that shouldn't happen.

**Closed** 2022-11-25 20:02 UTC
Labels: 🐞 bug
