### ISSUE TITLE
Filter app logs by instance ID

### ISSUE THREAD

**Issue by ayys** [wasmerio/wasmer#4699] opened 2024-05-15 07:28 UTC
App logs are generated on Edge. These logs can potentially come from many instances, so getting all the logs from many instances can be cumbersome.

One solution can be to display the instance ID along with the log entries in `wasmer app logs ..` subcommand, and allow users to filter for specific instance IDs via

```
wasmer app logs --instance <instance-id> ...
```

**Comment by theduke** [comment] 2024-06-20 09:56
Duplicate of #4416

**Closed by theduke** 2024-06-20 09:56 UTC
