### ISSUE TITLE
How to build wasmer with Docker?

### ISSUE THREAD

**Issue by leonardas103** [wasmerio/wasmer#970] opened 2019-11-14 23:12 UTC
I am following the Dockerfile Documentation, I do ```docker build -t wasmer --target=wasmer .``` and get the following error:
```
Step 11/15 : RUN cargo build --release
 ---> Running in b2c70e118733
error: failed to parse manifest at `/home/circleci/wasmer/Cargo.toml`

Caused by:
  the `default-run` manifest key is unstable

Caused by:
  feature `default-run` is required

this Cargo does not support nightly features, but if you
switch to nightly channel you can add
`cargo-features = ["default-run"]` to enable this feature
```
So I do what it says, modify the ```Cargo.toml``` adding ```cargo-features = ["default-run"]``` at the top. And modify ```Dockerfile``` changing ```cargo build --release``` to ```cargo +nightly build --release```. 

Ran the docker build again and got a new error:
```
error: toolchain 'nightly-x86_64-unknown-linux-gnu' is not installed
```
So I ensured that it is installed by doing:
```
rustup update
rustup install nightly
rustup toolchain install nightly
rustup toolchain install nightly-x86_64-unknown-linux-gnu
```
I ran the docker build again and the toolchain error persisted. Here I decided to run ```cargo build --release``` to see if the problem is somehow docker related, everything compiled fine, but I got the warning:
```
warning: /home/ubuntu/wasmer/Cargo.toml: the cargo feature `default-run` is now stable and is no longer necessary to be listed in the manifest
```
This contradicts the first error. What am I doing wrong?

**Comment by MarkMcCaskey** [comment] 2019-11-15 01:09
Thanks for reporting this!

The issue is that the dockerfile is using a version of Rust that we don't support!

`FROM circleci/rust:1.33.0-stretch as wasmer-build-env`

This should be changed to be using 1.38!

**Comment by syrusakbary** [comment] 2019-11-15 03:23
@leonardas103 we just fixed this on master.

Let us know if you have any further issues!

**Comment by leonardas103** [comment] 2019-11-15 08:39
This fixed the last error, but a new error popped up:
```
Step 11/15 : RUN cargo build --release
 ---> Running in 1d7f8d45ff66
error: failed to read `/home/circleci/wasmer/examples/plugin-for-example/Cargo.toml`

Caused by:
  No such file or directory (os error 2)
```
It seems for some reason this file is not being copied. How can I cd to the docker virtual path```/home/circleci/wasmer/``` to manually copy it?

**Comment by syrusakbary** [comment] 2019-11-15 17:48
This should be fixed now :)

**Closed** 2019-11-15 17:47 UTC
Labels: ❓ question
