### ISSUE TITLE
wasmer-cli: installation error on wsl2

### ISSUE THREAD

**Issue by harisraharjo** [wasmerio/wasmer#2931] opened 2022-06-06 05:31 UTC
### Describe the bug
I tried to install wasmer-cli via `cargo install wasmer-cli` but it doesn't work. It produces the following error `failed to run custom build command for "xkbcommon-sys v0.7.5"`. 
After that I tried to install it via curl. It installed successfully but doesn't seem to be working. it produces the following error `error while loading shared libraries: libtinfo.so.5: cannot open shared object file: No such file or directory` and ` wasmer was installed, but doesn't seem to be working :(`

## Fix
To fix this I have to get libtinfo5 for my wsl2 distro. But this is not documented anywhere. Maybe we could add a documentation for this?

**Comment by epilys** [comment] 2022-06-06 12:00
Duplicate of:
* https://github.com/wasmerio/wasmer/issues/2920
* https://github.com/wasmerio/wasmer/issues/2921

**Closed by epilys** 2022-06-06 12:00 UTC
Labels: 🐞 bug
