### ISSUE TITLE
Error : running wasmer aot file

### ISSUE THREAD

**Issue by subhakr** [wasmerio/wasmer#5009] opened 2024-08-13 05:14 UTC
### Describe the bug
 

After compiling wamser to aot (i.e, wasmc), when running the .wasmc  i am getting error 

![image](https://github.com/user-attachments/assets/7415733a-2c53-4aaa-bc46-fe7563cd1b7d)

wasmer -vV;
wasmer 4.3.1 (d5df452 2024-05-23)
binary: wasmer-cli
commit-hash: d5df452d22110593f12fcc0e152a0435344b6590
commit-date: 2024-05-23
host: x86_64-unknown-linux-gnu
compiler: singlepass,cranelift,llvm

rustc -vV
rustc 1.80.1 (3f5fd8dd4 2024-08-06)
binary: rustc
commit-hash: 3f5fd8dd41153bc5fdca9427e9e05be2c767ba23
commit-date: 2024-08-06
host: x86_64-unknown-linux-gnu
release: 1.80.1
LLVM version: 18.1.7

### Steps to reproduce
To compile wasmer to aot
 
`$ wasmer compile hi.wasm -o hi.wasmc`
 
To run :
 
`$ wasmer run hi.wasmc`

### Expected behavior

Wasmer should execute the .wasmc.

### Actual behavior

error: module hash is not present in the artifact.
![image](https://github.com/user-attachments/assets/662feb02-a9a3-45af-838a-17593a024710)

**Comment by syrusakbary** [comment] 2024-08-13 10:28
This is a duplicate of #5006. Closing this issue in favor of the older one

**Closed by syrusakbary** 2024-08-13 10:28 UTC
