### ISSUE TITLE
GLIBC_2.27 error on Amazon Linux 2

### ISSUE THREAD

**Issue by hassan-shahbazi** [wasmerio/wasmer#1970] opened 2020-12-25 22:50 UTC
### Describe the bug

When I try to install wasmer on a docker image of _Amazon Linux 2_, I get the following error:

`.wasmer/bin/wasmer: /lib64/libm.so.6: version 'GLIBC_2.27' not found (required by .wasmer/bin/wasmer)`

Which is because the latest version of _Amazon Linux 2_ comes with `glibc-2.26-39`. Since it is practically impossible to update `glibc`, the error makes wasmer completely broken on this distribution.

```bash
$ /etc/os-release

NAME="Amazon Linux"
VERSION="2"
ID="amzn"
ID_LIKE="centos rhel fedora"
VERSION_ID="2"
PRETTY_NAME="Amazon Linux 2"
ANSI_COLOR="0;33"
CPE_NAME="cpe:2.3:o:amazon:amazon_linux:2"
HOME_URL="https://amazonlinux.com/"
```

### Steps to reproduce
- Pull Amazon Linux docker image `docker pull amazonlinux`
- run the image `docker run -it amazonlinux /bin/bash`
- install required dependencies `yum install -y curl ....`
- run the installer `curl https://get.wasmer.io -sSfL | sh`

**Comment by jubianchi** [comment] 2021-01-05 11:06
Hello @hassan-shahbazi!

Thanks for reporting this issue.

I'm actually working on trying to resolve this but this may be a bit hard. Amazon Linux is using an "old" `glibc` version which does not exist in our build environment.

I'm trying to se if we can do something like what we did here: https://github.com/wasmerio/wasmer/pull/1746

**Comment by jubianchi** [comment] 2021-01-06 22:19
Hello @hassan-shahbazi, I just did a test build to see if I can solve the compatibility issue and it works. I did not do any extensive testing for now so the only thing I know is the binary starts and seems to work.

The artifact is here if you want to test: https://github.com/jubianchi/wasmer/suites/1780968135/artifacts/34044553

I'll continue testing it tomorrow and see if it really works and if it does not introduce regressions on other environments. If everything is OK, I'll update our CI pipeline.

**Comment by hassan-shahbazi** [comment] 2021-01-07 08:40
Thanks @jubianchi. It's great, thanks. I try to test it soon

**Comment by syrusakbary** [comment] 2021-01-20 23:03
Not sure why it was closed. Reopening the issue

**Comment by Hywan** [comment] 2021-07-16 13:33
I believe it's solved with https://github.com/wasmerio/wasmer/pull/1755. I'm closing the issue, but if the problem isn't solved, please @hassan-shahbazi, reopen the issue :-)!

**Closed by Hywan** 2021-07-16 13:33 UTC
Labels: 🐞 bug
