### ISSUE TITLE
str::from_utf8().ok() return Option::None on Result::Ok

### ISSUE THREAD

**Issue by xofyarg** [wasmerio/wasmer#421] opened 2019-05-03 21:57 UTC
### Describe the bug

When is string is generated from a slice on top of guest memory, calling the `.ok()` method on a successful `Result` return a `None` instead of `Some(&str)`. 

### Steps to reproduce

1. Clone repo https://github.com/wasmerio/wasmer-rust-example.git
2. Apply following patch:
```
diff --git a/wasm-sample-app/src/lib.rs b/wasm-sample-app/src/lib.rs
index 9e5fdb1..2fe7baa 100644
--- a/wasm-sample-app/src/lib.rs
+++ b/wasm-sample-app/src/lib.rs
@@ -31,4 +31,10 @@ pub extern fn hello_string_from_rust(ptr: i32, len: i32) {
     unsafe {
       print_str(out_str.as_ptr(), out_str.len());
     }
+
+    let string_result = str::from_utf8(&slice);
+    let out_str = format!("Result {:?}, Option {:?}", string_result, string_result.ok());
+    unsafe {
+      print_str(out_str.as_ptr(), out_str.len());
+    }
 }
\ No newline at end of file
```
3. `cd wasm-sample-app && cargo build --release && cd .. && cargo run --example string`

### Expected behavior

```
Hello from Rust!
Result Ok("from Rust!"), Option Some("from Rust!")
```

### Actual behavior

```
Hello from Rust!
Result Ok("from Rust!"), Option None
```

Feel free to close if not related.

**Comment by xmclark** [comment] 2019-05-06 16:16
Thank you for reporting! I can reproduce the issue. 

I think this can be demonstrated without using the additional print statement. Calling `ok()` does not act as expected. This is the variation of the function that also breaks:
```
#[no_mangle]
pub extern fn hello_string_from_rust(ptr: i32, len: i32) {
    let slice: &[u8] = unsafe { slice::from_raw_parts(ptr as _, len as _) };
    // this works
    let s1 = str::from_utf8(&slice);
    s1.unwrap();
    // this does not work
    let s2 = str::from_utf8(&slice);
    let s2_ok = s2.ok();
    s2_ok.unwrap(); // panics
}
```

The [source for result](https://doc.rust-lang.org/src/core/result.rs.html#334-339) indicates that there is a simple match occurring. I tried explicitly writing the match like this, and it works correctly:
```
let s = match string_result {
  Ok(x)  => Some(x),
  Err(_) => panic!(""), // never panics when string_result is Ok(_)
};
```

I generated the wasm as wat for the parts in the first example:
```
#[no_mangle]
pub extern fn hello_string_from_rust(ptr: i32, len: i32) {
    let slice: &[u8] = unsafe { slice::from_raw_parts(ptr as _, len as _) };
    // this works
    let s1 = str::from_utf8(&slice);
    s1.unwrap();
}
```

```
#[no_mangle]
pub extern fn hello_string_from_rust(ptr: i32, len: i32) {
    let slice: &[u8] = unsafe { slice::from_raw_parts(ptr as _, len as _) };
    // this does not work
    let s2 = str::from_utf8(&slice);
    let s2_ok = s2.ok();
    s2_ok.unwrap(); // panics
}
```

Diffing the generated wasm (as wat) shows quite a few differences. It may take some time to unpack the diffs, but my guess is this is a target wasm32-unknown-unknown bug. It may already be reported as an issue on Rust.

**Comment by MarkMcCaskey** [comment] 2019-06-06 21:06
Okay, I just did some investigation and here's what I found:

I was not able to reproduce this with native Rust:
```Rust
use std::{slice, str};

fn get_slice() -> (*mut u8, usize) {
    let mut vec: Vec<u8> = vec![];
    for byte in b"test" {
        vec.push(*byte);
    }
    let len = vec.len();
    (
        Box::leak(vec.into_boxed_slice()) as *mut [u8] as *mut u8,
        len,
    )
}

fn main() {
    let (ptr, len) = get_slice();
    let slice = unsafe { slice::from_raw_parts(ptr as _, len as _) };
    let s2 = str::from_utf8(&slice[..]);
    println!("{:?}", s2.ok());
    let s2_ok = match s2 {
        Ok(v) => {
            println!("in Ok {:?}", v);

            Some(v)
        }
        Err(e) => {
            println!("{:?}", e);

            None
        }
    };
    println!("{:?}", s2_ok);
}
```
does not seem to trigger the error.


The cause seems to be the inferred lifetime:
```Rust
let s2_ok = match s2 {
        Ok(v) => {
            let suc_str = format!("in Ok {:?}", v);
            unsafe {
                print_str(suc_str.as_ptr(), suc_str.len());
            }

            Some(v)
        }
        Err(e) => {
            let err_str = format!("{:?}", e);
            unsafe {
                print_str(err_str.as_ptr(), err_str.len());
            }
            None
        }
    };
```
the Ok branch is hit, but s2_ok is `None`.  My guess is that this is due to the binary representation of binary representation of Option: that `v` gets Dropped and set to null which is the same as None.

Notably
```
let s2_ok = match &s2 {
        Ok(v) => {
            let suc_str = format!("in Ok {:?}", v);
            unsafe {
                print_str(suc_str.as_ptr(), suc_str.len());
            }

            Some(v)
        }
        Err(e) => {
            let err_str = format!("{:?}", e);
            unsafe {
                print_str(err_str.as_ptr(), err_str.len());
            }
            None
        }
    };
```
does work exactly as expected.  But `.ok()` is defined without `&` in the match

**Comment by syrusakbary** [comment] 2019-08-05 21:38
It seems the responses for this issue should solve it.

@xofyarg let us know if that's not the case and we will revisit it.
Closing the issue

**Closed by syrusakbary** 2019-08-05 21:38 UTC
Labels: 🐞 bug

**Comment by xofyarg** [comment] 2019-08-06 01:26
The code segment only has issue in wasm32, and I believe there's something different inside `str::from_utf8`. Feel free to close if it not related to wasmer, but this issue can still be reproduced.
