### ISSUE TITLE
windows support

### ISSUE THREAD

**Issue by xmclark** [wasmerio/wasmer#51] opened 2018-12-12 01:08 UTC
There seem to be a few barriers to windows support. There is an outstanding bug on [`wabt-rs`](https://github.com/pepyakin/wabt-rs/issues/20) that prevents building on windows. There is a hacky work around, but non-ideal.

The codebase also seems to import many linux-only libraries, so those would have to refactored or conditionally compiled. 

Windows support would be a big win for portability, which I imagine is a priority for a tool that aims to be a cross-platform wasm runtime.

**Comment by pepyakin** [comment] 2018-12-12 11:51
It is a shame that wabt-rs doesn't work for Windows. Would love to help, but I don't have much experience with Windows nor have I a windows machine.

**Comment by syrusakbary** [comment] 2018-12-15 05:38
@pepyakin no worries, we will help you on that creating a PR on `wabt-rs` when the time comes :)

@xmclark we just added `Virtual memory allocation on Windows` with #54, so we are one step closer to be on windows :)

**Comment by xmclark** [comment] 2018-12-15 07:05
@syrusakbary that’s all great news! 

I’ve already started the ball rolling with @pepyakin on [windows support](https://github.com/pepyakin/wabt-rs/pull/31).

I’m also investigating signal support in libc for windows. Seems doable.

**Comment by xmclark** [comment] 2018-12-20 04:16
I think `libc` should have basic signals support on windows as of [this commit](https://github.com/rust-lang/libc/commit/027d4834615cf8bce3faa9c4a1c2706413a7b275). It may require more tinkering. 

I have spent the last few hours getting familiar with the details of stdio capture on windows. I think this is possible with just `libc` but it may be dirty. Time will tell! I am interested in any ideas for capture on windows.

**Comment by xmclark** [comment] 2018-12-21 02:40
@syrusakbary I think I have a solution for capturing the stdio, but I can't help feel that capturing stdio in-process seems a little round-about. A problem is windows pipes don't seem to be buffered and that has made it a bit more compilcated. The WinAPI has buffered pipes, but it would be a completely different implementation from the `libc pipe` implementation.

How about storing the tests in a test executable crate and spawning it from integration tests? The standard output can be captured with normal safe rust. There is no platform specific code or unsafe code. I can't imagine the performance is any worse. Thoughts?

**Comment by syrusakbary** [comment] 2019-02-14 18:34
We added experimental Windows, so it can run WebAssembly files.

There is still some work to do regarding Emscripten (#176) but other than that everything is tested and green 🎉.

We are preparing for Wasmer 0.2.0 and will close this issue once we publish the wasmer.exe file :)

**Comment by CryZe** [comment] 2019-02-14 23:58
Okay, so I was able to test it today and it seems like it does work for the most part. However there is something that seems to be broken. In my wasm file I have an exported function that returns a f64 value and that does not seem to be returned correctly by wasmer. I'm getting some garbage value on the host side. I'm not sure if that's just a windows abi mismatch or if this affects Linux and co. as well.

**Comment by xmclark** [comment] 2019-02-15 00:03
@CryZe I am glad you're able to try it out! Could you post an issue that reproduces your problem?

**Comment by CryZe** [comment] 2019-02-15 00:03
Yeah I'll open a full issue with a reproducible example (and maybe tested on Linux too) in a bit.

**Comment by syrusakbary** [comment] 2019-02-25 22:22
We just published Wasmer 0.2.0 -> https://github.com/wasmerio/wasmer/releases/tag/0.2.0
The new crates are also published.

We created a separate issue to implement the emscripten syscalls in Windows #176.

Here's a useful PR that updates the [wasmer-rust-example](https://github.com/wasmerio/wasmer-rust-example) to the [new 0.2.0 API](https://github.com/wasmerio/wasmer-rust-example/pull/5/files).

Closing the issue :)

**Closed by syrusakbary** 2019-02-25 22:23 UTC
Labels: enhancement, help wanted
