### ISSUE TITLE
Operations fail when the root (/) is mapped to a directory

### ISSUE THREAD

**Issue by RReverser** [wasmerio/wasmer#2098] opened 2021-02-06 03:28 UTC
### Describe the bug

Compile this sample:

```rust
fn main() {
	std::fs::write("/file.tmp", "").unwrap();
}
```

and run it with `/` mapped to arbitrary dir, e.g.:

```sh
$ wasmer run temp.wasm --mapdir /::.
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: PermissionDenied, message: "Permission denied" }', temp.rs:2:37
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
error: failed to run `temp.wasm`
│   1: WASI execution failed
│   2: failed to run WASI `_start` function
│   3: RuntimeError: unreachable
           at __rust_start_panic (temp.wasm[178]:0x6d9f)
           at rust_panic (temp.wasm[171]:0x6a4a)
           at std::panicking::rust_panic_with_hook::h2345fb0909b53e12 (temp.wasm[166]:0x6724)
           at std::panicking::begin_panic_handler::{{closure}}::h2b823a1363a03a2d (temp.wasm[154]:0x5f2b)
           at std::sys_common::backtrace::__rust_end_short_backtrace::hb0622d3d366790b9 (temp.wasm[153]:0x5ee5)
           at rust_begin_unwind (temp.wasm[165]:0x652a)
           at core::panicking::panic_fmt::hfd8f6f23831ae610 (temp.wasm[230]:0xbd47)
           at core::option::expect_none_failed::hcc29812858326774 (temp.wasm[245]:0xc8c9)
           at core::result::Result<T,E>::unwrap::he06d871e1e4fdffe (temp.wasm[50]:0x1035)
           at temp::main::hdc57b3c35eac1777 (temp.wasm[30]:0xb27)
           at core::ops::function::FnOnce::call_once::he8b767bce28da76f (temp.wasm[37]:0xc61)
           at std::sys_common::backtrace::__rust_begin_short_backtrace::h6387731889f92761 (temp.wasm[23]:0x8bc)
           at std::rt::lang_start::{{closure}}::hce8463864adfec48 (temp.wasm[45]:0xea1)
           at std::rt::lang_start_internal::h260050c92cd470af (temp.wasm[172]:0x6b5b)
           at std::rt::lang_start::h0e04eac24e9adb47 (temp.wasm[44]:0xe75)
           at __original_main (temp.wasm[31]:0xb58)
           at _start (temp.wasm[9]:0x400)
╰─> 4: unreachable
```

Same binary works and creates file successfully with Wasmtime:

```sh
$ wasmtime run temp.wasm --mapdir /::.
$ ls file.tmp
file.tmp
```

If I try to create a file in a subdirectory instead:

```rust
fn main() {
	std::fs::write("/tmp/file.tmp", "").unwrap();
}
```

then it also fails, but with a different error - "invalid argument" instead of "permission denied":

```sh
$ mkdir tmp
$ wasmer run temp.wasm --mapdir /::.
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 28, kind: InvalidInput, message: "Invalid argument" }', temp.rs:2:41
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
error: failed to run `temp.wasm`
│   1: WASI execution failed
│   2: failed to run WASI `_start` function
│   3: RuntimeError: unreachable
           at __rust_start_panic (temp.wasm[178]:0x6d9f)
           at rust_panic (temp.wasm[171]:0x6a4a)
           at std::panicking::rust_panic_with_hook::h2345fb0909b53e12 (temp.wasm[166]:0x6724)
           at std::panicking::begin_panic_handler::{{closure}}::h2b823a1363a03a2d (temp.wasm[154]:0x5f2b)
           at std::sys_common::backtrace::__rust_end_short_backtrace::hb0622d3d366790b9 (temp.wasm[153]:0x5ee5)
           at rust_begin_unwind (temp.wasm[165]:0x652a)
           at core::panicking::panic_fmt::hfd8f6f23831ae610 (temp.wasm[230]:0xbd47)
           at core::option::expect_none_failed::hcc29812858326774 (temp.wasm[245]:0xc8c9)
           at core::result::Result<T,E>::unwrap::he06d871e1e4fdffe (temp.wasm[50]:0x1035)
           at temp::main::hdc57b3c35eac1777 (temp.wasm[30]:0xb27)
           at core::ops::function::FnOnce::call_once::he8b767bce28da76f (temp.wasm[37]:0xc61)
           at std::sys_common::backtrace::__rust_begin_short_backtrace::h6387731889f92761 (temp.wasm[23]:0x8bc)
           at std::rt::lang_start::{{closure}}::hce8463864adfec48 (temp.wasm[45]:0xea1)
           at std::rt::lang_start_internal::h260050c92cd470af (temp.wasm[172]:0x6b5b)
           at std::rt::lang_start::h0e04eac24e9adb47 (temp.wasm[44]:0xe75)
           at __original_main (temp.wasm[31]:0xb58)
           at _start (temp.wasm[9]:0x400)
╰─> 4: unreachable
```

While it also works with Wasmtime successfully.

Finally, only if I rerun last binary with selective mapping like `/tmp::./tmp` instead of `/::.`, then it works even with Wasmer:

```sh
$ wasmer run temp.wasm --mapdir /tmp::./tmp
$ ls tmp
file.tmp
```

So it seems that it's specifically `--mapdir /::...` mapping that throws Wasmer off in all cases.

### Versions

```sh
$ echo "`wasmer -V` | `rustc -V` | `uname -m`"
wasmer 1.0.2 | rustc 1.41.0 (5e1a79984 2020-01-27) | x86_64
```

**Comment by Hywan** [comment] 2021-02-06 07:17
Thanks for the bug report. We will take a look at it!

**Comment by MarkMcCaskey** [comment] 2021-02-08 14:48
Thanks for filing this issue!

This is a bit of a tough one as there's no obviously correct behavior here given what Wasmer does with `/`.  Better error messages at the very least seem like a reasonable step forward if we keep the behavior the same. (error messages at the UI level of CLI flags / `WasiStateBuilder`)

Quick background info: `/` is the virtual root that Wasmer adds by default, all preopened directories go here. The permissions around `/` are restricted for good reason. This is Wasmer-specific and was useful for working around bugs in common WASI implementations as well as being a generally useful way to talk about preopened directories.

The reason it works in other Wasm runtimes is because they don't open a directory by default at the root called `/`. Wasmer would likely behave the same without that extra logic. While the virtual root, `/`, is not part of the WASI spec, WASI is pretty underspecified, so without a spectest or something explicitly prohibiting it, I don't think it's necessarily wrong. My reasoning here is that most of the way our WASI implementation works came from reverse engineering / making existing WASI modules work, cross-referenced with what exists of the WASI documentation too. This virtual root made a lot more WASI modules work (even though that was likely due to bugs in their implementation), thus it was a useful thing for us to add.

So the tl;dr is that `/` in particular will cause you a lot of problems if you try to use it directly in a lot of situations. What we should do about it is unclear. If the bugs in some of those common WASI implementations are now fixed, maybe the trade-off isn't worth it and we should remove the entire concept, but it may still be generally useful.

--------

Side note: there's been discussion in the WASI CG recently about official WASI spectests. With official spectests specifying behavior precisely, I'm happy to make pretty much any change necessary to make wasmer conform to the standard behavior. So that would be an easy path forward if this was covered. In the absence of well-defined behavior here though, we'll have to make our own judgement call.


Either way, this is a relatively old feature now in our WASI implementation and it should definitely get some more attention given how much has changed since it was first added.

**Comment by RReverser** [comment] 2021-02-11 20:26
> without a spectest or something explicitly prohibiting it, I don't think it's necessarily wrong

I don't think I can agree. WASI explicitly allows any path prefixes, any custom restrictions on top of that are mismatches between implementation (in this case Wasmer) and the spec.

From the way you're describing `/` as special, does this also mean I can't map `/some/nested/path` in Wasmer without mapping `/some` first? That would be also odd, because, again, any prefix should be fine and allowed.

**Comment by MarkMcCaskey** [comment] 2021-02-11 20:43
I agree that the current extra logic around `/` is probably not ideal, especially if the changes we have make us incompatible with other tools.

> I don't think I can agree. WASI explicitly allows any path prefixes, any custom restrictions on top of that are mismatches between implementation (in this case Wasmer) and the spec.

I'd love to be proven wrong here, but this doesn't match my recollection. Much of the behavior of WASI is unspecified other than in wasi-libc / WASI modules that are compiled by it. If you find a link to WASI docs that, explicitly or not, specifies behavior related to that, please share it here. I just quickly skimmed over the WASI repo and wasn't able to find any info about this, but I easily could have missed it.

> From the way you're describing / as special, does this also mean I can't map /some/nested/path in Wasmer without mapping /some first? That would be also odd, because, again, any prefix should be fine and allowed.

I think the only issue here is the use of `/` in the front. Things will be implicitly put in `/`, so Wasmer should do the same thing if you try to use an alias of `/abc` or `/abc/def/...`

Upon further reflection, we could probably just ignore the leading `/` and do the right thing here. I wonder why we don't do that already.

**Comment by RReverser** [comment] 2021-02-12 12:30
> If you find a link to WASI docs that, explicitly or not, specifies behavior related to that, please share it here.

You're right that there isn't a great explicit spec for this, but https://github.com/bytecodealliance/wasmtime/blob/5c1d728e3ae8ee7aa329e294999a2c3086b21676/docs/WASI-overview.md#capability-oriented does say

> However, the WASI libc implementation still does provide an implementation of open, by taking the approach of libpreopen. Programs may be granted capabilities for directories on launch, and the library maintains a mapping from their filesystem path to the file descriptor indices representing the associated capabilities. When a program calls open, they look up the file name in the map, and automatically supply the appropriate directory capability.

Neither this doc, nor libpreopen put any restrictions on which directories can be used as mapping points, so I still think that any should be permitted since they're not explicitly restricted otherwise.

> Upon further reflection, we could probably just ignore the leading `/` and do the right thing here. I wonder why we don't do that already.

Sounds reasonable.

**Comment by RReverser** [comment] 2021-02-12 12:32
I totally agree such example should be added to https://github.com/khronosproject/wasi-test to avoid confusion though.

**Comment by k-nasa** [comment] 2021-04-24 10:21
I couldn't reproduce this problem. Has this issue been fixed? Or is it because the version of rustc is different?

```
❯ cat src/main.rs
fn main() {
    std::fs::write("/file.tmp", "hogehoge").unwrap();
}

❯ cargo build --target=wasm32-wasi
   Compiling wasmer-bug-check v0.1.0 (/Users/wantedly333/lab/sandbox/wasm_sandbox/wasmer-bug-check)
    Finished dev [unoptimized + debuginfo] target(s) in 1.05s

❯ wasmer run target/wasm32-wasi/debug/wasmer-bug-check.wasm --mapdir /::.

❯ cat file.tmp
hogehoge

echo "`wasmer -V` | `rustc -V` | `uname -m`"
wasmer 1.0.2 | rustc 1.53.0-nightly (6df26f897 2021-04-20) | x86_64
```

**Comment by Hywan** [comment] 2021-07-16 13:56
I cannot reproduce neither.
Closing. Please @RReverser, feel free to reopen if you still face the problem.

**Closed by Hywan** 2021-07-16 13:56 UTC
Labels: 🐞 bug, 📦 lib-wasi

**Comment by malaow3** [comment] 2023-06-07 01:29
Looking to re-open as I'm having the same issue presented previously

![image](https://github.com/wasmerio/wasmer/assets/20196976/eb53e0b8-7026-4c50-846e-7b625d493e45)
