### ISSUE TITLE
The `--mapdir` command seems ignored when running a package

### ISSUE THREAD

**Issue by ptitSeb** [wasmerio/wasmer#4027] opened 2023-06-23 14:51 UTC
For this test, I created a folder `blah` in my current folder, and put a simple `index.php` in there with the following content:

```php
<?  phpinfo();
```

Try to run this file using a packaged version of `php` built for `wasm32-wasix`, using:

```bash
wasmer run php/php --net --mapdir /blah:$(pwd)/blah --  -S localhost:8001 -t /blah
```

The server will not start with the error:

```
Directory /blah does not exist.
```

While the same command using a local naked wasm file works.

**Comment by Michael-F-Bryan** [comment] 2023-07-10 04:00
As mentioned [on Slack](https://wasmerio.slack.com/archives/C02CK7101PG/p1688960922797099), I think this may be something do to with the `php.wasm` file rather than runners or the filesystem.

I'm reproducing everything on the current `master`, 07198b9e7d952c3135ff315bc16900647d3bab95, with the following local files:

```console
$ tree /tmp/app
/tmp/app
└── index.php

1 directory, 1 file

$ cat /tmp/app/index.php
<?  phpinfo();
```

When I ran `php/php@7.4.31` using `wasmer run`, I saw the same `Directory "/" does not exist` error.

```console
$ RUST_BACKTRACE=1 cargo run --package=wasmer-cli --features=compiler,singlepass,cranelift --release -- \
        run php/php@7 --net --cranelift --registry=wasmer.io --mapdir=/app:/tmp/app -- \
        -S localhost:8000 -t /app

Directory /app does not exist.
```

However, using the same `--mapdir` command and the `python/python` package to inspect the filesystem shows me that `/app/` does exist and you can freely access `/app/index.php`.

```console
$ RUST_BACKTRACE=1 cargo run --package=wasmer-cli --features=compiler,singlepass,cranelift --release -- \
        run python/python --net --cranelift --registry=wasmer.io --mapdir=/app:/tmp/app

Python 3.6.7 (default, Feb 14 2020, 03:17:48)
[Wasm WASI vClang 9.0.0 (https://github.com/llvm/llvm-project 0399d5a9682b3cef7 on generic
Type "help", "copyright", "credits" or "license" for more information.
>>> import os
>>> os.listdir("/")
['.app', '.private', 'app', 'bin', 'dev', 'etc', 'lib', 'tmp']
>>> os.listdir("/app/")
['index.php']
>>> open("/app/index.php").read()
'<?  phpinfo();\n'
```

I don't know if it's related, but I noticed that we seem to be trying to config read files from `/home/seb/`. I'm guessing when we built the package, it hard-coded certain configuration files that are present on the build machine.

```console
$ RUST_BACKTRACE=1 cargo run --package=wasmer-cli --features=compiler,singlepass,cranelift --release -- \
        run php/php@7 --net --cranelift --registry=wasmer.io --mapdir=/app:/tmp/app -vv -- \
        -S localhost:8000 -t /app
...
2023-07-10T03:45:55.539315Z DEBUG ThreadId(13) path_open: wasmer_wasix::syscalls::wasi::path_open: return=Errno::noent dirfd=6 follow_symlinks=true path="/home/seb/php7/lib/php-cli-server.ini"
2023-07-10T03:45:55.539349Z DEBUG ThreadId(13) path_open: wasmer_wasix::syscalls::wasi::path_open: return=Errno::noent dirfd=6 follow_symlinks=true path="/home/seb/php7/lib/php.ini"
2023-07-10T03:45:55.541186Z DEBUG ThreadId(13) path_open: wasmer_wasix::syscalls::wasi::path_open: return=Errno::noent dirfd=6 follow_symlinks=true path="/usr/local/ssl/openssl.cnf"
```

**Comment by Michael-F-Bryan** [comment] 2023-07-10 08:37
@ptitSeb and I did [some more debugging](https://wasmerio.slack.com/archives/C02CK7101PG/p1688977034957009) and we think it might be an issue with `wasix-libc`.

Running the above Python commands with `wasmer/python@3.12.0-build.5` and logging all syscalls shows something really interesting:

```py
Python 3.12.0a7+ (heads/wasix-compatibility-dirty:22ad54d11a, May 30 2023, 13:05:09) [Clang 16.0.0 ] on wasix
Type "help", "copyright", "credits" or "license" for more information.
>>> import os
>>> os.listdir("/app/")
2023-07-10T08:16:09.975681Z DEBUG ThreadId(13) path_open: wasmer_wasix::syscalls::wasi::path_open: return=Errno::noent dirfd=4 follow_symlinks=true path="p/"
>>> os.listdir("////app/")
2023-07-10T08:20:51.237988Z DEBUG ThreadId(13) path_open: wasmer_wasix::syscalls::wasi::path_open: return=Errno::success dirfd=4 follow_symlinks=true path="/app/" ret_fd=13
['index.php']
>>> open("////app/index.php").read()
'<?  phpinfo();\n'
```

The `path=` thing is logged [here](https://github.com/wasmerio/wasmer/blob/5c8e76c85e67b976a64cd0349a1118b6808d9209/lib/wasix/src/syscalls/wasi/path_open.rs#L69-L70) and then passed to the filesystem, so if we are seeing `path="p/"` instead of `path="/app/"` that indicates the guest program was giving us a bad pointer. Using `////app/` (i.e. `/app/` prefixed with `"/app".len() - 1` slashes) works because we are pushing the `/app/` further down the buffer. 

@ptitSeb checked using `/blah` as the mounted path (i.e. length of 5, rather than `/app`'s 4) and found that he had to prepend the path with one more slash (i.e. `wasmer run wasmer/python --net --mapdir blah:$(pwd)/blah -- /////blah/test.py`).

**Comment by Michael-F-Bryan** [comment] 2023-08-29 08:53
This was fixed in https://github.com/wasix-org/wasix-libc/commit/1347deccf7f3e1263122cf5ec6c54e4ed85942f4.

**Closed by Michael-F-Bryan** 2023-08-29 08:53 UTC
Labels: priority-high
