### ISSUE TITLE
Ubuntu 20.04 (focal): Missing system dependency libtinfo.so.5

### ISSUE THREAD

**Issue by asaaki** [wasmerio/wasmer#1651] opened 2020-09-27 07:23 UTC
### Describe the bug

Under (at least) Ubuntu 20.04 users won't be able to run `wasmer` without manually installing `libtinfo5`.
For a truely standalone executable the assumed environment dependencies should be very narrow or absent; I guess Ubuntu is a prime candidate to challenge such assumptions regularly.

```sh
echo "`wasmer -V` | `rustc -V` | `uname -m`"

wasmer 1.0.0-alpha3 | rustc 1.46.0 (04488afe3 2020-08-24) | x86_64
```

#### Extended environment info

I'm running Ubuntu on a Windows 10 machine via WSL2, but my hard guess is that this is only a Ubuntu issue alone.
It is not too uncommon that with new release cycles some dependencies get bumped and break executables not installed via the package manager (aka _fetched from somewhere in the internet_).

```sh
$ uname -a
Linux kattegat-win 4.19.128-microsoft-standard #1 SMP Tue Jun 23 12:58:10 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

```sh
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.1 LTS
Release:        20.04
Codename:       focal
```

### Steps to reproduce

1. Open a Ubuntu 20.04 environment
2. In a shell run installation as described by the readme: `curl https://get.wasmer.io -sSfL | sh`
3. The following error message displays after installation:

```
/home/asaaki/.wasmer/bin/wasmer: error while loading shared libraries: libtinfo.so.5: cannot open shared object file: No such file or directory
error: wasmer was installed, but doesn't seem to be working :(
```

### Expected behavior

Installation and execution of `wasmer` succeeds without having to resolve the assumed dependencies manually.

### Actual behavior

Installation partially succeeds, execution fails.

```
# installation error
/home/asaaki/.wasmer/bin/wasmer: error while loading shared libraries: libtinfo.so.5: cannot open shared object file: No such file or directory
error: wasmer was installed, but doesn't seem to be working :(
```

```
# execution error
 wasmer -V
wasmer: error while loading shared libraries: libtinfo.so.5: cannot open shared object file: No such file or directory
```

#### Manual fix by user possible

Manually fixable by running the following command:

```sh
sudo apt install libtinfo5
```

The manual fix is an okay hack for users familar with Ubuntu systems in particular.
But we should not assume such knowledge and skills.

**Comment by mejedi** [comment] 2020-10-02 15:12
Same issue on Ubuntu 19.10.

**Comment by MarkMcCaskey** [comment] 2020-10-13 18:31
I think this should be fixed now, we fixed it right after releasing `alpha4` but you can try it with a release from Wasmer-nightly https://github.com/wasmerio/wasmer-nightly/releases ; we don't currently have a way to install directly from wasmer-nightly like we do with standard Wasmer but it's on the list of things we want to do

**Comment by syrusakbary** [comment] 2020-10-30 06:31
This issue is now fixed, and the latest distributed version of Wasmer no longer has the issue.

Closing :)

**Closed by syrusakbary** 2020-10-30 06:31 UTC
Labels: 🐞 bug, 📦 lib-compiler-llvm

**Comment by leon-thomm** [comment] 2022-05-11 12:08
still running into this on Kubuntu 21.10, I tried installing via `curl https://get.wasmer.io -sSfL | sh ` as suggested on the website

`sudo apt install libtinfo5` worked

**Comment by heyjdp** [comment] 2022-05-11 12:19
Many thanks for submitting this Kubuntu data point. The issue is well known and we are working on a solution. I shall leave this ticket closed because issues https://github.com/wasmerio/wasmer/issues/2822 and https://github.com/wasmerio/wasmer/issues/2716 are open and tracking this challenge.

**Comment by ratulb** [comment] 2022-10-30 23:19
error while loading shared libraries: libtinfo.so.5: cannot open shared object file: No such file or directory
error: wasmer was installed, but doesn't seem to be working :(


DISTRIB_DESCRIPTION="Ubuntu 20.04.5 LTS"
NAME="Ubuntu"
VERSION="20.04.5 LTS (Focal Foss)
