### ISSUE TITLE
headless stand-alone binary?

### ISSUE THREAD

**Issue by nomeata** [wasmerio/wasmer#1990] opened 2021-01-06 15:26 UTC
### Summary

Is there a small `wasmer-run` binary that can run pre-compiled `.wjit` or `.so` files?

### Additional details

The post at https://medium.com/wasmer/wasmer-1-0-3f86ca18c043 got me curious about running pre-compiled Wasm binaries on Amazon Lambda, as it claims

> With our newly-added support for AOT (Ahead Of Time) compilation, you can run a “headless” version of Wasmer that weighs just a few hundred kilobytes and runs any precompiled Wasm binary on any device.

I was expecting some stripped-down `wasm` binary that can only run, but not compile, but I could not find it (the makefile only mentiones headless related to the C-API). Am I maybe missing something?

**Comment by nomeata** [comment] 2021-01-06 15:35
With
```
cargo build --release --manifest-path lib/cli/Cargo.toml --no-default-features --features wasi,native
```
or `… wasi,jit` I get an 11MB executable, which is much better than 70MB, but not quite “few hundred kilobytes”.

**Comment by MarkMcCaskey** [comment] 2021-01-06 15:46
This is a good question! We don't have an official build of headless wasmer yet... I know in the past we've made binaries of Wasmer much, much smaller than that, but it did require a bit of tinkering to remove things like panic unwinding and debug printing. I suspect until cargo supports custom build profiles on stable it'll be hard to ship a proper release of it unless we apply a diff on the repo and rebuild or something.

Since we've announced it, I'll look into this a bit more when I have some time

**Comment by MarkMcCaskey** [comment] 2021-01-07 16:19
Alright so I looked into it a bit and a few things needed some minor tweaks, but we're able to get an x86_64 macos binary to 779,064 bytes, compiled with the `native` and `wasi` features. With binary compression that can get down to 282,640 bytes but there's a known issue preventing that from working on macos Big Sur right now and binary compression is fairly extreme anyways, so probably not what most people would want to do most of the time.

I think there's a lot of slightly higher, but still low hanging fruit to drop a few hundred more kb off of that 779kb, but that'll require some minor code / cargo.toml changes. And after that there are a few more things I'm aware of to really strip it down even further, but those might be higher effort.

These are the top contributors by crate:

```
12.8%  22.0% 147.8KiB clap
11.9%  20.4% 136.9KiB std
11.3%  19.4% 129.9KiB wasmer_wasi
 4.8%   8.2%  55.3KiB wasmer_cli
 4.8%   8.2%  55.0KiB wasmer_engine_native
 3.2%   5.5%  37.0KiB wasmer
 2.2%   3.8%  25.5KiB wasmer_vm
 1.9%   3.2%  21.4KiB rustc_demangle
 1.0%   1.8%  11.9KiB wasmer_engine
 0.9%   1.5%  10.0KiB wasmer_compiler
 0.6%   1.0%   6.8KiB rand_chacha
 0.6%   1.0%   6.8KiB anyhow
 0.6%   0.9%   6.4KiB target_lexicon
 0.5%   0.9%   6.1KiB [Unknown]
 0.4%   0.6%   4.3KiB colored
 0.3%   0.5%   3.7KiB backtrace
 0.3%   0.5%   3.1KiB wasmer_types
 0.2%   0.3%   2.0KiB distance
 0.2%   0.3%   1.7KiB ansi_term
 0.1%   0.2%   1.5KiB hashbrown
 ```
 
If we want to make wasmer as small as possible, removing `clap` entirely and replacing it with something more lightweight is likely the only option, but we can also definitely reduce the size of clap over what we have now.

Similarly, I believe `wasmer_wasi` could be made significantly smaller with a bit of focused effort, same with `wasmer-cli`, it contains a ton of code that wouldn't be relevant to headless mode. That unused code in wasmer-cli is transitively keeping lots of other code in all the other crates "alive" meaning it must also be included in the binary.

-------

To reproduce this, update a version of nightly, install `xargo` and add

```toml
[profile.release]
opt-level = 'z'
debug = false
debug-assertions = false
overflow-checks = false
lto = true
panic = 'abort'
incremental = false
codegen-units = 1
rpath = false
 ```
 
 to the bottom of the top level Cargo.toml
 
 Then put
 
 ```toml
 [dependencies]
std = {default-features=false, features=["panic_immediate_abort"]}
 ```
 
 into Xargo.toml (we use `xargo` to rebuild the stdlib with our custom release profile / get better dead code elimination by rebuilding it)
 
 then disable logging in `lib/wasi/Cargo.toml` by adding changing the tracing line to 
 ```tracing = { version = "0.1", features = ["release_max_level_off", "max_level_off"] }``` (I'll ship a better fix for this later) -- most of the size of WASI comes from log statements.
 
 Then run
 
 ```sh
 xargo build --target=x86_64-apple-darwin --release --manifest-path=lib/cli/Cargo.toml --no-default-features --features native,wasi
 strip target/x86_64-apple-darwin/release/wasmer
 ls -laB target/x86_64-apple-darwin/release | grep wasmer
 ```

-------

Small binary size hasn't been a big focus for us yet, but I think there's actually a lot we could do if we wanted to really make it small, I think sub 500kb is very achievable. And going further than that might require disabling features / really thinking about it.

**Comment by MarkMcCaskey** [comment] 2021-01-15 15:15
With the release of 1.0.1, we are now shipping a minified `wasmer-headless`!

There's still more work to be done in regards to making it even smaller and writing about headless wasmer use cases, but I'll close this issue for now as I think the original question is answered!

Thanks for pinging us about this -- it's easy for things to slip through the cracks with all the things going on!

**Closed by MarkMcCaskey** 2021-01-15 15:15 UTC
Labels: ❓ question
