### ISSUE TITLE
macOS support use llvm-10 backend to compile capi failed

### ISSUE THREAD

**Issue by bxq2011hust** [wasmerio/wasmer#1509] opened 2020-07-24 07:15 UTC
### Describe the bug

```sh
echo "`wasmer -V` | `rustc -V` | `uname -m`"
```

```bash
rustc 1.44.1 (c7087fe00 2020-06-17) | x86_64
```

### Steps to reproduce

1. Go to wasmer source dir
2. `brew install llvm` and `export PATH="/usr/local/opt/llvm/bin:$PATH"`
3. modify line 34 of Makefile as `ifneq (, $(findstring 8,$(LLVM_VERSION))$(findstring 9,$(LLVM_VERSION))$(findstring 10,$(LLVM_VERSION)))`
4. Compile with make capi-llvm
5. See error

### Expected behavior

compile success

### Actual behavior

failed

### Additional context

```bash
$ make capi-llvm
Available backends: cranelift llvm
cargo build --manifest-path lib/runtime-c-api/Cargo.toml --release \
		--no-default-features --features llvm-backend,wasi
   Compiling inkwell_internals v0.1.0
error: failed to run custom build command for `inkwell_internals v0.1.0`

Caused by:
  process didn't exit successfully: `/Users/baixingqiang/WorkSpace/git/wasmer/target/release/build/inkwell_internals-9dc5a45deff1bf0d/build-script-build` (exit code: 101)
--- stderr
thread 'main' panicked at 'Unable to load Cargo manifest!: Error(Hyper(Error(Connect, Os { code: 61, kind: ConnectionRefused, message: "Connection refused" })), "https://raw.githubusercontent.com/TheDan64/inkwell/master/Cargo.toml")', /Users/baixingqiang/.cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/inkwell_internals-0.1.0/build.rs:9:37
stack backtrace:
   0:        0x10995a78f - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h8ad47541fb823094
   1:        0x10997dd8e - core::fmt::write::he23e9bd6497f06c3
   2:        0x109954837 - std::io::Write::write_fmt::h91528f1131e6004e
   3:        0x10995c7ea - std::panicking::default_hook::{{closure}}::h1983f014a45a477e
   4:        0x10995c52c - std::panicking::default_hook::hb0d9b93b5be8b120
   5:        0x10995cdb8 - std::panicking::rust_panic_with_hook::h9f3faafe0983de5c
   6:        0x10995c982 - rust_begin_unwind
   7:        0x10998f70f - core::panicking::panic_fmt::h0a2d1b3ca0b14316
   8:        0x10998f615 - core::result::unwrap_failed::h71fe5d08237d0e52
   9:        0x10967c32a - build_script_build::main::heca91a831bf05049
  10:        0x1096786b6 - std::rt::lang_start::{{closure}}::h1984c6e90814fb23
  11:        0x10995d1e9 - std::rt::lang_start_internal::h795af50241e12334
  12:        0x10967c429 - main

make: *** [capi-llvm] Error 101
```

**Comment by syrusakbary** [comment] 2020-09-01 14:01
This issue seem to be caused by inkwell, but it should be resolved on the latest code we have in `master` (since it's using the fixed version of inkwell).

Closing issue

**Closed by syrusakbary** 2020-09-01 14:01 UTC
Labels: 🐞 bug
