### ISSUE TITLE
feat(vm) Add support for iOS

### ISSUE THREAD

**Issue by Connoropolous** [wasmerio/wasmer#1832] opened 2020-11-22 05:05 UTC
### Summary

Is IOS on the roadmap for wasmer anywhere, and if so does it have a predicted timeline? 
I noted there is VERY recent support for the new apple silicon chips. 

### Additional details

I was trying to compile a project with a dependency on (https://github.com/holochain/holochain) (with target `aarch64-apple-ios` ) which has a dependency currently on `wasmer-runtime-core v0.16.2` and discovered that we can't build wasmer-runtime-core for that target. 

Holochain uses wasmer for executing apps built on their p2p framework... and I am interested in running those p2p apps in native ios applications.

This was the issue that was popping up when I tried...
```
error[E0425]: cannot find function `get_fault_info` in this scope
   --> /Users/x/.cargo/registry/src/github.com-1ecc6299db9ec823/wasmer-runtime-core-0.16.2/src/fault.rs:285:21
    |
285 |         let fault = get_fault_info(siginfo as _, ucontext);
    |                     ^^^^^^^^^^^^^^ not found in this scope
```

**Comment by MarkMcCaskey** [comment] 2020-11-24 21:26
Hey @Connoropolous, we hope to run Wasmer pretty much everywhere in the future!

However, iOS in particular is fairly tricky as Apple does not allow JITs in the app store. However it should be possible to use precompiled Wasm modules with Wasmer or execute the Wasm without a JIT.

You might have better luck with Wasmer 1.0.0-alpha* releases of Wasmer / the latest version on master, but I imagine there's likely to be more cases similar to the one you ran into above.

**Comment by Connoropolous** [comment] 2020-11-24 22:09
@MarkMcCaskey thanks for the info! On latest releases has it been tried to compile for apple-ios targets, or are you confident from your background knowledge that it won't work? (I will try if you haven't tried, just to see)

**Comment by syrusakbary** [comment] 2020-11-24 22:14
The issue is not that it won't work, but that Apple have never approved any app in the store that uses JIT compilation techniques.

However, the JIT restriction might have changed in iOS 14.2 - https://9to5mac.com/2020/11/06/ios-14-2-brings-jit-compilation-support-which-enables-emulation-apps-at-full-performance/

So I'd encourage you to try it out and post here your findings!

**Comment by Connoropolous** [comment] 2020-11-26 02:56
My first findings suggest there would need to be PRs put through to make it happen, it's not quite there. Good to hear that Apple could open to this.

error: unsupported platform
   --> /Users/x/code/rsm/wasmer/lib/vm/src/trap/traphandlers.rs:209:21
    |
209 |                     compile_error!("unsupported platform");
    |                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
error[E0425]: cannot find function `pthread_getattr_np` in crate `libc`
    --> /Users/connor/code/rsm/wasmer/lib/vm/src/trap/traphandlers.rs:94:19
     |
94   |               libc::pthread_getattr_np(this_thread, &mut thread_attrs);
     |                     ^^^^^^^^^^^^^^^^^^ help: a function with a similar name exists: `pthread_getname_np`
     |
    ::: /Users/connor/.cargo/registry/src/github.com-1ecc6299db9ec823/libc-0.2.73/src/unix/bsd/apple/mod.rs:3393:5
     |
3393 | /     pub fn pthread_getname_np(
3394 | |         thread: ::pthread_t,
3395 | |         name: *mut ::c_char,
3396 | |         len: ::size_t,
3397 | |     ) -> ::c_int;
     | |_________________- similarly named function `pthread_getname_np` defined here

error[E0425]: cannot find function `pthread_attr_getstack` in crate `libc`
    --> /Users/connor/code/rsm/wasmer/lib/vm/src/trap/traphandlers.rs:97:19
     |
97   |             libc::pthread_attr_getstack(&thread_attrs, &mut stackaddr, &mut stacksize);
     |                   ^^^^^^^^^^^^^^^^^^^^^ help: a function with a similar name exists: `pthread_attr_destroy`
     |
    ::: /Users/connor/.cargo/registry/src/github.com-1ecc6299db9ec823/libc-0.2.73/src/unix/mod.rs:1089:5
     |
1089 |     pub fn pthread_attr_destroy(attr: *mut ::pthread_attr_t) -> ::c_int;
     |     -------------------------------------------------------------------- similarly named function `pthread_attr_destroy` defined here

error[E0308]: mismatched types
   --> /Users/connor/code/rsm/wasmer/lib/vm/src/trap/traphandlers.rs:194:52
    |
194 |         unsafe fn get_pc(cx: *mut libc::c_void) -> *const u8 {
    |                   ------                           ^^^^^^^^^ expected *-ptr, found `()`
    |                   |
    |                   implicitly returns `()` as its body has no tail or `return` expression
    |
    = note: expected raw pointer `*const u8`
                 found unit type `()`

error: aborting due to 4 previous errors

**Comment by panicfrog** [comment] 2021-04-18 14:23
in the [website,](https://wasmer.io/) i found that the wasmer can run on iOS Android, how to do that?

**Comment by kkk669** [comment] 2021-04-22 10:45
@panicfrog You misunderstood about it. It just says that WebAssembly can run on iOS, not Wasmer.

**Comment by NathHorrigan** [comment] 2021-07-25 13:13
Hi @Hywan ,

I've seen you've had some activity on this issue.

I've been trying to compile Wasmer to iOS using the dylib engine but having issues with each compiler that I use.

Currently I'm trying LLVM but once I drag the `libwasmer.a` file to Xcode and run I get the following error. Any ideas?

```
ld: in /.../example/ios/libwasmer.a(Scalar.cpp.o), archive member 'Scalar.cpp.o' with length 19360 is not mach-o or llvm bitcode for architecture arm64
```

**Comment by Hywan** [comment] 2021-08-12 13:38
Can be kinda relevant #2516.

**Comment by syrusakbary** [comment] 2021-09-01 14:56
As of this PR: #2535 we now support iOS on Wasmer `master` (the version `2.0.1`/`2.1.0` will be released soon

**Closed by syrusakbary** 2021-09-01 14:56 UTC
Labels: 🎉 enhancement, 📦 lib-vm

**Comment by afa7789** [comment] 2022-04-13 19:51
https://wasmer.io/posts/wasmer-2.1 
https://stackoverflow.com/questions/68963743/how-to-use-wasmer-in-ios
