### ISSUE TITLE
Validate wasi get_inode_at_path Logic 

### ISSUE THREAD

**Issue by theduke** [wasmerio/wasmer#3911] opened 2023-05-25 13:03 UTC
Validate that the changes from #3867 are correct.

From @john-sharratt 

> yeah the code works (i also tested it) its just that first bit of the if statement is redundant (its never true and so always passes)

**Comment by ptitSeb** [comment] 2023-06-06 09:26
It seems to be working as intended, so closing.

**Closed by ptitSeb** 2023-06-06 09:26 UTC
Labels: priority-medium, needs-tests
