### ISSUE TITLE
WASI state serialization doesn't preserve unread stdin bytes

### ISSUE THREAD

**Issue by MarkMcCaskey** [wasmerio/wasmer#754] opened 2019-09-04 23:19 UTC
When serializing WASI state we ignore unread stdin bytes.

Maybe this is the correct behavior?  This needs design and more thought before we can fix it.

See #726 for more context

**Comment by Hywan** [comment] 2021-07-15 09:54
I believe it is the correct and expected behavior. Serializing is not used to “pause” the runtime in this context, but rather to “save” the compiled module, to later re-instantiating it quickly. Keeping the stdin bytes would be a terrible behavior in this context because the execution context would be totally different. I'm closing this issue :-).

**Closed by Hywan** 2021-07-15 09:54 UTC
Labels: 🐞 bug
