### ISSUE TITLE
c-api: getting a string from a wasm_val_t

### ISSUE THREAD

**Issue by smolck** [wasmerio/wasmer#2577] opened 2021-09-21 03:29 UTC
### Summary

To get my feet wet with the C API, I tried to set up a `print` import for wasm to use like so:
```c
static wasm_trap_t *print(const wasm_val_vec_t* args, wasm_val_vec_t* results) {
    wasm_val_t val = args->data[0];

    wasm_memory_t *mem = wasm_ref_as_memory(val.of.ref);
    byte_t *bytes = wasm_memory_data(mem);

    printf("called from wasm: %s", bytes);
    wasm_memory_delete(mem);

    return NULL;
}
```
For the sake of brevity, I've left out the rest of the setup for adding this as an import to a wasm module etc.

However, this fails to compile with `Undefined symbols for architecture x86_64: "_wasm_ref_as_memory"`. Is that intended? And if so, what is the proper way to receive a string on the C side from a wasm module?

This seems to be a similar issue to/the same issue as that mentioned in the https://github.com/wasmerio/wasmer/discussions/2052 discussion, but that hasn't had much activity recently.

**Comment by syrusakbary** [comment] 2021-10-20 12:17
Closing the issue as duplicate of #2615. We will follow-up there

**Closed by syrusakbary** 2021-10-20 12:17 UTC
Labels: ❓ question
