### ISSUE TITLE
wasmer run saghul/quickjs

### ISSUE THREAD

**Issue by syrusakbary** [wasmerio/wasmer#3351] opened 2022-11-22 01:32 UTC
This doesn't work. Stdin/stdout is currently broken.

We need to verify this works after merging #3344

**Comment by fschutt** [comment] 2022-11-22 09:43
Potential duplicate of #3349

**Comment by fschutt** [comment] 2022-11-28 07:22
Works after merging #3344.

**Closed by fschutt** 2022-11-28 07:22 UTC
Labels: 🐞 bug, priority-high
