### ISSUE TITLE
C-API: undefined reference to `wasmer_last_error_length()'

### ISSUE THREAD

**Issue by Dakror** [wasmerio/wasmer#1952] opened 2020-12-17 19:36 UTC
### Describe the bug

Using the C-API on x64 Linux on Version 1.0.0-beta2, i can't use the C-API functions to retrieve compilation errors.

### Steps to reproduce

I've simply copy pasted the error-fetching code that is in the comments of wasmer_wasm.h and tried to compile it. These are the only functions that don't seem to link.

### Expected behavior

No linking error :D

**Comment by Hywan** [comment] 2020-12-18 12:39
Hello,

Thanks for reporting an issue. However, can you point to the code that fails, or explain how you did compile the code? All our examples (even the C ones) are tested, I'm curious!

**Comment by Dakror** [comment] 2020-12-19 14:04
I'm using Wasmer using CMake's external project using the release tar.gz: 

```
include(ExternalProject)

# Get wasmer
ExternalProject_Add(
    wasmer_src
    PREFIX "vendor/wasmer"  
    URL https://github.com/wasmerio/wasmer/releases/download/1.0.0-beta2/wasmer-linux-amd64.tar.gz
    BUILD_COMMAND ""
    INSTALL_COMMAND ""
    CONFIGURE_COMMAND ""
    CMAKE_COMMAND ""
    UPDATE_COMMAND ""
    BUILD_BYPRODUCTS <SOURCE_DIR>/lib/libwasmer.a
)

# Prepare wasmer
ExternalProject_Get_Property(wasmer_src source_dir)
set(wasmer_INCLUDE_DIR ${source_dir}/include)
set(wasmer_LIBRARY_PATH ${source_dir}/lib/libwasmer.a)
file(MAKE_DIRECTORY ${wasmer_INCLUDE_DIR})
add_library(wasmer STATIC IMPORTED)
set_property(TARGET wasmer PROPERTY IMPORTED_LOCATION ${wasmer_LIBRARY_PATH})
set_property(TARGET wasmer APPEND PROPERTY INTERFACE_INCLUDE_DIRECTORIES ${wasmer_INCLUDE_DIR})

# Dependencies
add_dependencies(wasmer wasmer_src)
```

and then in the simplest example possible:

```cxx
#include <wasmer_wasm.h>

int main() {
    int len = wasmer_last_error_length();
    return 0;
}
```


compiled with (by CMake) `/bin/c++ -g -O0 -fsanitize=address  wasmer-test.cc.o  -o wasmertest libwasmer.a  -pthread`

results in 

```
[build] /usr/bin/ld: wasmer-test.cc.o: in function `main':
[build] wasmer-test.cc:4: undefined reference to `wasmer_last_error_length()'
```

**Comment by Dakror** [comment] 2020-12-19 14:37
Working on some other parts of my code i also discovered that i can't link against these functions: 

```
wasm_table_get
wasm_ref_as_func_const
```

**Comment by Dakror** [comment] 2020-12-19 14:58
I've now also tried it using Wasmer compiled from source, and im getting the same errors.

**Comment by Dakror** [comment] 2020-12-19 15:07
You mentioned the tests, so i went and looked: 
 Turns out the test file that the wasm functions i referred to is not being run when testing:

https://github.com/wasmerio/wasmer/blob/b11a3831f75971874bc567ec611f4f4c9e2acdf5/lib/c-api/tests/Makefile#L27

**Comment by syrusakbary** [comment] 2020-12-19 18:28
The `wasmer_last_error_length` function is now part of the deprecated API.

We are moving toward the standard wasm-c-api.
You can find an example of how to use traps with it here:
https://github.com/wasmerio/wasmer/blob/master/lib/c-api/tests/wasm-c-api/example/trap.c

> Turns out the test file that the wasm functions i referred to is not being run when testing:
> ```
> wasm-c-api/example/finalize			wasm-c-api/example/hostref
> ```

You are right! There are some parts of the wasm-c-api that are not yet fully integrated, but they will be soon!

Let us know if you have any more questions!

**Comment by Dakror** [comment] 2020-12-19 19:07
Thank you for clarifying, looking forward to the implementation of the rest of the functions!

**Comment by Dakror** [comment] 2020-12-19 19:08
What function can there be used in the future then to retrieve compilation errors?

**Comment by MarkMcCaskey** [comment] 2020-12-21 14:34
It's not standard, but we do update the wasmer error in our Wasm C API implementation as well because the Wasm C API by itself doesn't have an error reporting mechanism.  So `wasmer_last_error_length` and the other error function should both work.  If the symbols can't be found then that sounds like a bug!

**Comment by MarkMcCaskey** [comment] 2020-12-22 15:45
Alright, I'm looking into this now, it looks like on x86_64 macos the static wasmer library has both of these symbols... I'm not sure why it'd be missing, I'll investigate the ones we released

**Comment by MarkMcCaskey** [comment] 2020-12-22 16:52
As far as I can tell, the symbols are included in both the mac x86_64 and and linux x86_64 beta2 releases in both static and dynamic library form.

The only thing suspicious is that the address of some functions in the linux static library appeared as `0` with `nm` on macos:

```
 834   │ 0000000000000000 T wasmer_last_error_length
 835   │ 0000000000000000 T wasmer_last_error_message
 ```
 
 I'm not sure what's going on there, but I pinged someone about it

**Comment by MarkMcCaskey** [comment] 2020-12-22 17:05
Follow up, it is address in in the compilation unit it was in, adding `-o` to the `nm` command revealed this.

Can you provide more specifics / run `nm` on your library to check that it has these symbols?

**Comment by Dakror** [comment] 2020-12-22 19:54
in the static library im seeing

```
0000000000000000 T wasmer_last_error_length
0000000000000000 T wasmer_last_error_message
```

in the shared i see
```
00000000000861f0 T wasmer_last_error_length
0000000000086200 T wasmer_last_error_message
```

**Comment by chances** [comment] 2020-12-27 10:28
@syrusakbary Is there an issue tracking this? https://github.com/wasmerio/wasmer/issues/1952#issuecomment-748508494

I'm trying to use functions related to `wasm-c-api/example/hostref`.

**Comment by nlewycky** [comment] 2021-01-26 10:23
The library is defining `wasmer_last_error_length` and `wasmer_last_error_message` as `nm` says they are, the problem is that those aren't the names the C++ code is looking for. From the error, 
```
[build] wasmer-test.cc:4: undefined reference to `wasmer_last_error_length()'
```
that's actually a symbol named `_Z24wasmer_last_error_lengthv` being pretty-printed by running it through `c++filt _Z24wasmer_last_error_lengthv`. If it were just the symbol name, it wouldn't have the empty parentheses on the end because for names that aren't mangled in C++, we don't know their parameters.

wasmer_wasm.h needs to wrap all its declarations in an `extern "C"{ /* ... */ }` block.

**Closed** 2021-01-27 20:51 UTC
Labels: 🐞 bug, 📦 lib-c-api
