### ISSUE TITLE
Fortran support?

### ISSUE THREAD

**Issue by chadbr** [wasmerio/wasmer#930] opened 2019-11-04 23:18 UTC
We have a lot of fortran code -- I'd love to get it into WASM / Wasmer... any ideas?

**Comment by MarkMcCaskey** [comment] 2019-11-05 19:05
Hi @chadbr !

I'm not very familiar with fortran, but it's likely that there are fortran compilers with an LLVM backend or a backend that already supports Wasm.  If that's the case, then it shouldn't be very hard to output Wasm from your fortran code.  After searching around a bit, it looks like it was possible to use Emscripten to do this a few years ago!

Wasmer, the CLI tool, supports WASI and Emscripten (version 1.38.43 and lower) right now.

Wasmer, the library, supports WASI, Emscripten, ABI-less WASM, and any custom ABI you care to implement!

So to clarify a bit more, Wasmer will run any valid Wasm.  The issue is in terms of ABIs.  The ABIs are the interface by which the Wasm can interact with the user's computer (such as printing, reading files, sending networking requests, getting random numbers, or anything that's not pure computation).  If you plan to embed Wasmer in your application, you can supply these host-calls for the ABI yourself, allowing you to define any kind of system you want.  There are a few standard ones which we have good support for too!

Let me know if that's not clear or if you have any issues!

**Comment by MarkMcCaskey** [comment] 2019-11-11 22:00
I'm going to close this now as the next steps for getting Fortran working with Wasmer are on the Fortran compiler side (it may already work) and not on the Wasmer side.  Feel free to reopen or respond if something comes up.

**Closed by MarkMcCaskey** 2019-11-11 22:00 UTC
Labels: 🎉 enhancement

**Comment by chadbr** [comment] 2019-11-11 23:36
Thanks @MarkMcCaskey  - will look into it.

**Comment by SugarRayLua** [comment] 2022-05-15 16:39
Does Wasiconfigure/wasicc work with Fortran?

Hello. I’m a novice programmer who recently started trying out web assembly on my iMac (x86, OSX Monterey) with the goal of porting some wasm code to my iPad and running it there (via the iPad a-shell app). However, when I tried to use wasiconfigure to configure and build R from source, it gave me the following Fortran errors:

checking for dummy main to link with Fortran libraries… none
checking for Fortran name-mangling scheme… unknown
configure: WARNING: unknown Fortran name-mangling scheme
checking whether gfortran appends underscores to external names… unknown
configure: error: cannot use Fortran

Yet, when wasiconfigure initially started configuring R, it did recognize there was a Fortran compiler:

looking for a modern Fortran compiler
checking for gfortran… gfortran
checking whether the compiler supports GNU Fortran… yes
checking whether gfortran accepts -g… yes

However, when I try to configure R for building by using regular clang, there are no Fortran configuration errors and the configure script succeeds in making a makefile (e.g. CC= clang ./configure).

I appreciate any information you can provide on this matter.

Thanks!
