### ISSUE TITLE
wasmer-c-api docs are not on docs.rs

### ISSUE THREAD

**Issue by MarkMcCaskey** [wasmerio/wasmer#2016] opened 2021-01-13 17:41 UTC
They should be.

I suspect this is due to wasmer-c-api's build.rs breaking the model that cargo expects: we can't generate files outside of the target directory.

**Comment by Hywan** [comment] 2021-01-22 13:01
Duplicate of https://github.com/wasmerio/wasmer/issues/1954. Closing :-).

**Closed by Hywan** 2021-01-22 13:01 UTC
Labels: 🐞 bug, 📚 documentation, 📦 lib-c-api
