### ISSUE TITLE
Adding initializer for C-API: wasm_func_new_with_env to initialize env with instance

### ISSUE THREAD

**Issue by antJack** [wasmerio/wasmer#2023] opened 2021-01-15 03:51 UTC
Is there any way to obtain the wasmer instance in the host function that exported to wasm module?

It seems that the C-API "wasm_func_new_with_env" only supports trivial env, which means that the env can not obtain and hold information about wasmer instance.

In contrast, we could implement "WasmerEnv::init_with_instance" in Rust to fill the rust env with the wasmer instance.

Therefore, I suggest adding an initializer for C-API "wasm_func_new_with_env" to allow initialize the env with the wasmer instance:

```rust
#[no_mangle]
pub unsafe extern "C" fn wasm_func_new_with_env(
    store: Option<&wasm_store_t>,
    function_type: Option<&wasm_functype_t>,
    callback: Option<wasm_func_callback_with_env_t>,
    env: *mut c_void,
    //
    // adding an env initializer, for example:  
    //
    // initializer: Option<wasm_env_initializer_t>
    // 
    // pub type wasm_env_initializer_t = unsafe extern "C" fn(
    //     *mut c_void, 
    //     *wasm_instance_t
    // ) -> some_ret;
    // 
    finalizer: Option<wasm_env_finalizer_t>,
) -> Option<Box<wasm_func_t>> {
    let store = store?;
    let function_type = function_type?;
    let callback = callback?;

    let func_sig = &function_type.inner().function_type;
    let num_rets = func_sig.results().len();

    //
    // implement WasmerEnv::init_with_instance for WrapperEnv if 'initializer' is not nil
    //
    #[derive(wasmer::WasmerEnv, Clone)]
    #[repr(C)]
    struct WrapperEnv {
        env: *mut c_void,
        finalizer: Option<wasm_env_finalizer_t>,
    };

    // ...
}
```

**Comment by Hywan** [comment] 2021-01-15 09:09
It is related to this feature request, https://github.com/wasmerio/wasmer-go/issues/173.

The environment passed to `wasm_func_new_with_env` supports any kind of environment (it's a `void*` after all). The issue is that the instance is created _after_ the host function is created, so we can't use a closure or store the instance in the host function env's.

I'll think about it and come back to you :-).

**Comment by Hywan** [comment] 2021-02-04 12:51
I think it's not possible with our current C API.

First problem is `WasmerEnv::init_with_instance` receives a `&Instance`. We can't build a `wasm_instance_t` from that as we would need to get an `Arc<Instance>`. And that's only the first problem. A deep one.

The second problem is that we would need to “find” the `wasm_instance_t` field in the user-defined environment to set it up correctly… which is not possible.

The third problem (an alternative to the second problem) would be to define another `wasm_new_func_with_env` function specifically to receive a `wasm_instance_t` as a _n_th argument. We are going outside the standard here.

So I think the best solution for the moment is for the user to write something like:

```c
typedef struct my_env_t {
    wasm_instance_t* instance;
} my_env_t;

my_env_t* env = malloc(sizeof(my_env_t));

… = wasm_new_function_with_env(store, function_type, function_implementation, env, NULL);

wasm_instance_t* instance = wasm_instance_new(…);

env.instance = instance;
```

I think it's reasonable to ask a user to do that for the moment without deeply changing our Rust API, and without introducing a new non-standard C API.

What do you think? Is it an acceptable compromise?

**Comment by antJack** [comment] 2021-02-04 13:36
Thanks for replying.

My original question is that can we access the current instance within the imported func.

In the browser-like case (one instance per thread), we could do that by storing the instance into thread-local. However, we can not do that in Go. Therefore I opened this issue.

Lately, I realized that even we could initialize the env with the instance as I asked for in this issue, we still can not solve the original problem perfectly, since we may need to delay the creation of env until we create our instance.

And I found that the c-api may not unwilling to support the other cases (those apart from one instance per thread) in the short term: https://github.com/WebAssembly/wasm-c-api/issues/107

Finally, I solved my problem by doing a little hack (kind of like wasmer-go v0.3): inject the instance as the first arg for imported func.

**Comment by Hywan** [comment] 2021-02-15 09:01
I believe the code snippet I wrote in my previous comment is very likely to solve your problem. Am I mistaken? The code is similar in Go, with https://github.com/wasmerio/wasmer-go/issues/173#issuecomment-777464575.

I'm closing this issue since you said you've solved your problem. Feel free to reopen for further questions!

**Closed by Hywan** 2021-02-15 09:01 UTC
Labels: 🎉 enhancement, 📦 lib-c-api
