### ISSUE TITLE
Skip trap handling while executing imports

### ISSUE THREAD

**Issue by avasylev** [wasmerio/wasmer#866] opened 2019-10-07 17:09 UTC
### Motivation

Currently when embedding wasmer it's trap catches errors generated in imports code. These are not in wasm code and are not safe to handle by wasmer trap. Error message doesn't have clear indication if error was in wasm code or import, thus making it unsafe to continue execution after any trap.

### Proposed solution

Track wasm code / imports execution, and only handle trap when it was triggered from wasm code. Something like https://goo.gl/yMeyUY

**Comment by avasylev** [comment] 2019-10-18 17:45
#842 seems to be about the same issue, tracking that trap signal originated from within wasm vm boundries.

To clarify, yes I mean wasm imports, function pointer passed to wasmer_import_func_new. When such function is implemented in C++ (native, not wasm) and it triggers trap, wasmer should not catch such trap, but let it buble and crash the process (let host handler deal with trap).

**Comment by nlewycky** [comment] 2019-10-18 20:27
Got it! Yes, this will be fixed when we fix #842.

Duplicate of #842

**Comment by nlewycky** [comment] 2019-10-18 20:28
Duplicate of #842

**Comment by syrusakbary** [comment] 2020-07-17 20:07
This should be solved in the refactor.

**Comment by syrusakbary** [comment] 2020-08-24 22:08
We just landed the refactor in `master`. Closing the issue

**Closed by syrusakbary** 2020-08-24 22:08 UTC
Labels: resolved in wasmer refactor, 🎉 enhancement
