### ISSUE TITLE
C-API: "wasm_table_get" is declared, but not implemented

### ISSUE THREAD

**Issue by FGasper** [wasmerio/wasmer#2495] opened 2021-07-28 22:01 UTC
Apparently similar to #2486. `wasm.h` defines this function, but it’s not in `libwasmer.so`’s symbol table.

```
> readelf -s /usr/local/lib/libwasmer.so | grep wasm_table | awk '{print $8}' | sort | uniq
wasm_table_as_extern
wasm_table_copy
wasm_table_delete
wasm_table_grow
wasm_table_new
wasm_table_same
wasm_table_size
wasm_tabletype_as_externt
wasm_tabletype_delete
wasm_tabletype_element
wasm_tabletype_limits
wasm_tabletype_new
wasm_tabletype_vec_copy
wasm_tabletype_vec_delete
wasm_tabletype_vec_new
wasm_tabletype_vec_new_em
wasm_tabletype_vec_new_un
```

**Comment by MartinKolbAtWork** [comment] 2021-07-29 16:25
I'm missing `wasm_table_get` as well for my use-cases.
In addition I need `wasm_ref_as_func`, which is also defined by the headers, but an implementation is missing.

**Comment by syrusakbary** [comment] 2021-10-20 12:30
Closing this as duplicate of #2052

**Closed by syrusakbary** 2021-10-20 12:30 UTC
Labels: 🎉 enhancement, 📦 lib-c-api
