### ISSUE TITLE
UAF possible (though not likely in practice) with Memory::view

### ISSUE THREAD

**Issue by coolreader18** [wasmerio/wasmer#3567] opened 2023-02-02 17:41 UTC
### Describe the bug

Because the return type of `Memory::view` is tied to the lifetime of `self` and not the lifetime of the `store`, it's possible to use the `MemoryView` after the store (and therefore the actual memory buffer) has dropped.

### Steps to reproduce

```rust
let mut store = wasmer::Store::new(wasmer::Engine::headless());
let mem = wasmer::Memory::new(&mut store, wasmer::MemoryType::new(1, None, false))?;
let view = mem.view(&store);
view.write_u8(0x10, 42)?;
drop(store); // bye bye memories
let x = view.read_u8(0x10)?; // hello UAF :3
```

```
❯ cargo run
    Finished dev [unoptimized + debuginfo] target(s) in 0.05s
     Running `target/debug/testcase`
[1]    158432 segmentation fault (core dumped)  cargo run
```

### Additional context

wasmtime solves this issue by having the return of its equivalent function be tied just to the store parameter, not to the memory handle:
```rust
pub fn data<'a, T: 'a>(&self, store: impl Into<StoreContext<'a, T>>) -> &'a [u8]
```

**Comment by Michael-F-Bryan** [comment] 2023-04-12 09:14
I believe this is a duplicate of #3516.

**Closed by Michael-F-Bryan** 2023-04-12 09:14 UTC
Labels: bug, 🕵️ needs investigation, priority-high
